server:
  port: 8085
spring:
  application:
    name: chat-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:onfis_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres123}
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    com.onfis: DEBUG
