<?php
/**
 * Dashboard Page
 * Displays user dashboard with calendar showing quiz deadlines
 */

$showHeader = true;
$activePage = 'dashboard';
$title = 'Dashboard - ITS';
$defaultEventsPayload = htmlspecialchars(json_encode($quizEvents ?? []), ENT_QUOTES, 'UTF-8');
require_once __DIR__ . '/../layouts/header.php';
?>

<div
    id="page-dashboard"
    class="page active"
    data-events-url="<?= htmlspecialchars($calendarEventsUrl ?? '', ENT_QUOTES, 'UTF-8') ?>"
    data-default-events='<?= $defaultEventsPayload ?>'
>
    <div class="container">
        <!-- Sidebar -->
        <aside class="sidebar">
            <div class="sidebar-header">
                <button class="toggle-button" id="sidebar-toggle">
                    <i data-feather="menu"></i>
                </button>
            </div>
            <div class="sidebar-content">
                <div class="sidebar-nav-item active" data-section="dashboard">
                    <i data-feather="home"></i>
                    <span>Dashboard</span>
                </div>
                <div class="sidebar-nav-item" onclick="window.location.href='<?= BASE_URL ?>/course'">
                    <i data-feather="grid"></i>
                    <span>My Courses</span>
                </div>
                <div class="sidebar-nav-item category">
                    <span>Enrolled Courses</span>
                </div>
                <?php foreach ($courses ?? [] as $course): ?>
                <div class="sidebar-nav-item sub-item" onclick="window.location.href='<?= BASE_URL ?>/course/<?= $course['id'] ?>'">
                    <i data-feather="book"></i>
                    <span><?= htmlspecialchars($course['name']) ?></span>
                </div>
                <?php endforeach; ?>
            </div>
        </aside>
        
        <!-- Main Content -->
        <main class="main">
            <h1 class="course-title">Dashboard</h1>
            
            <div class="breadcrumbs">
                <a href="<?= BASE_URL ?>/">Home</a>
                <span>/</span>
                <span>Dashboard</span>
            </div>
            
            <!-- Welcome Section -->
            <div class="section expanded" style="margin-bottom: 30px;">
                <div class="section-header">
                    <div class="section-header-content">
                        <i class="arrow" data-feather="chevron-right"></i>
                        <span class="section-title">Welcome, <?= htmlspecialchars($userName ?? 'User') ?>!</span>
                    </div>
                </div>
                <div class="section-content">
                    <?php if ($error = \App\Core\Session::getFlash('error')): ?>
                        <div class="alert alert-danger"><?= htmlspecialchars($error) ?></div>
                    <?php endif; ?>
                    <p style="font-size: 16px; line-height: 1.7; color: #555;">
                        Welcome to your learning dashboard. Here you can see your upcoming quizzes and assignments.
                        <?php if ($isInstructor ?? false): ?>
                        You can manage your courses, create content, and grade student submissions.
                        <?php else: ?>
                        Navigate to your courses to view learning materials and complete assessments.
                        <?php endif; ?>
                    </p>
                </div>
            </div>
            
            <!-- Calendar Section -->
            <div class="calendar-container">
                <div class="calendar-header">
                    <h2 id="calendar-month-year">Loading...</h2>
                    <div class="nav-buttons">
                        <button class="button button-secondary" id="prev-month">
                            <i data-feather="chevron-left"></i>
                        </button>
                        <button class="button button-secondary" id="today-btn">Today</button>
                        <button class="button button-secondary" id="next-month">
                            <i data-feather="chevron-right"></i>
                        </button>
                    </div>
                </div>
                <div class="calendar-grid" id="calendar-grid">
                    <!-- Calendar will be generated by JavaScript -->
                </div>
            </div>
        </main>
    </div>
</div>

<?php require_once __DIR__ . '/../layouts/footer.php'; ?>
