<?php
/**
 * Dashboard Page
 * Displays user dashboard with calendar showing quiz deadlines
 */

$showHeader = true;
$activePage = 'dashboard';
$title = 'Dashboard - ITS';
require_once __DIR__ . '/../layouts/header.php';
?>

<div id="page-dashboard" class="page active">
    <div class="container">
        <!-- Sidebar -->
        <aside class="sidebar">
            <div class="sidebar-header">
                <button class="toggle-button" id="sidebar-toggle">
                    <i data-feather="menu"></i>
                </button>
            </div>
            <div class="sidebar-content">
                <div class="sidebar-nav-item active" data-section="dashboard">
                    <i data-feather="home"></i>
                    <span>Dashboard</span>
                </div>
                <div class="sidebar-nav-item" onclick="window.location.href='<?= BASE_URL ?>/course'">
                    <i data-feather="grid"></i>
                    <span>My Courses</span>
                </div>
                <div class="sidebar-nav-item category">
                    <span>Enrolled Courses</span>
                </div>
                <?php foreach ($courses ?? [] as $course): ?>
                <div class="sidebar-nav-item sub-item" onclick="window.location.href='<?= BASE_URL ?>/course/<?= $course['id'] ?>'">
                    <i data-feather="book"></i>
                    <span><?= htmlspecialchars($course['name']) ?></span>
                </div>
                <?php endforeach; ?>
            </div>
        </aside>
        
        <!-- Main Content -->
        <main class="main">
            <h1 class="course-title">Dashboard</h1>
            
            <div class="breadcrumbs">
                <a href="<?= BASE_URL ?>/">Home</a>
                <span>/</span>
                <span>Dashboard</span>
            </div>
            
            <!-- Welcome Section -->
            <div class="section expanded" style="margin-bottom: 30px;">
                <div class="section-header">
                    <div class="section-header-content">
                        <i class="arrow" data-feather="chevron-right"></i>
                        <span class="section-title">Welcome, <?= htmlspecialchars($userName ?? 'User') ?>!</span>
                    </div>
                </div>
                <div class="section-content">
                    <p style="font-size: 16px; line-height: 1.7; color: #555;">
                        Welcome to your learning dashboard. Here you can see your upcoming quizzes and assignments.
                        <?php if ($isInstructor ?? false): ?>
                        You can manage your courses, create content, and grade student submissions.
                        <?php else: ?>
                        Navigate to your courses to view learning materials and complete assessments.
                        <?php endif; ?>
                    </p>
                </div>
            </div>
            
            <!-- Calendar Section -->
            <div class="calendar-container">
                <div class="calendar-header">
                    <h2 id="calendar-month-year">Loading...</h2>
                    <div class="nav-buttons">
                        <button class="button button-secondary" id="prev-month">
                            <i data-feather="chevron-left"></i>
                        </button>
                        <button class="button button-secondary" id="today-btn">Today</button>
                        <button class="button button-secondary" id="next-month">
                            <i data-feather="chevron-right"></i>
                        </button>
                    </div>
                </div>
                <div class="calendar-grid" id="calendar-grid">
                    <!-- Calendar will be generated by JavaScript -->
                </div>
            </div>
        </main>
    </div>
</div>

<script>
    // Calendar data from PHP
    const quizEvents = <?= json_encode($quizEvents ?? []) ?>;
    
    let currentDate = new Date();
    
    function generateCalendar(year, month) {
        const monthNames = ["January", "February", "March", "April", "May", "June",
                           "July", "August", "September", "October", "November", "December"];
        const weekdays = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
        
        document.getElementById('calendar-month-year').textContent = `${monthNames[month]} ${year}`;
        
        const firstDay = new Date(year, month, 1).getDay();
        const daysInMonth = new Date(year, month + 1, 0).getDate();
        const daysInPrevMonth = new Date(year, month, 0).getDate();
        
        let html = '';
        
        // Weekday headers
        weekdays.forEach(day => {
            html += `<div class="calendar-weekday">${day}</div>`;
        });
        
        // Previous month's days
        for (let i = firstDay - 1; i >= 0; i--) {
            const day = daysInPrevMonth - i;
            html += `<div class="calendar-day other-month"><div class="day-number">${day}</div></div>`;
        }
        
        // Current month's days
        const today = new Date();
        for (let day = 1; day <= daysInMonth; day++) {
            const dateStr = `${year}-${String(month + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
            const dayEvents = quizEvents.filter(e => e.date === dateStr);
            
            // Check if this day is today
            let cellClass = 'calendar-day';
            if (day === today.getDate() && 
                month === today.getMonth() && 
                year === today.getFullYear()) {
                cellClass += ' today';
            }
            
            let eventsHtml = '';
            if (dayEvents.length > 0) {
                eventsHtml = '<div class="day-events">';
                dayEvents.forEach(event => {
                    eventsHtml += `<div class="day-event ${event.type}" title="${event.title}">${event.title}</div>`;
                });
                eventsHtml += '</div>';
            }
            
            html += `<div class="${cellClass}">
                        <div class="day-number">${day}</div>
                        ${eventsHtml}
                     </div>`;
        }
        
        // Next month's days
        const totalCells = Math.ceil((firstDay + daysInMonth) / 7) * 7;
        const remainingCells = totalCells - (firstDay + daysInMonth);
        for (let day = 1; day <= remainingCells; day++) {
            html += `<div class="calendar-day other-month"><div class="day-number">${day}</div></div>`;
        }
        
        document.getElementById('calendar-grid').innerHTML = html;
        feather.replace();
    }
    
    document.getElementById('prev-month').addEventListener('click', () => {
        currentDate.setMonth(currentDate.getMonth() - 1);
        generateCalendar(currentDate.getFullYear(), currentDate.getMonth());
    });
    
    document.getElementById('next-month').addEventListener('click', () => {
        currentDate.setMonth(currentDate.getMonth() + 1);
        generateCalendar(currentDate.getFullYear(), currentDate.getMonth());
    });
    
    document.getElementById('today-btn').addEventListener('click', () => {
        currentDate = new Date();
        generateCalendar(currentDate.getFullYear(), currentDate.getMonth());
    });
    
    // Sidebar toggle
    document.getElementById('sidebar-toggle').addEventListener('click', function() {
        document.querySelector('.container').classList.toggle('sidebar-collapsed');
    });
    
    // Initialize calendar
    generateCalendar(currentDate.getFullYear(), currentDate.getMonth());
</script>

<?php require_once __DIR__ . '/../layouts/footer.php'; ?>
